"""Write the scene hosts, the score element and the total duration into index.html from timeline.json.

    python3 tools/build_index.py

index.html must hold the markers `<!-- scenes:begin -->` and `<!-- scenes:end -->`, and the root
`data-composition-id="main"` element. Background tweens that span the whole film carry the comment
`/*total*/` or `/*half*/` after their duration, and they are rewritten too.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TL = json.load(open(os.path.join(ROOT, "timeline.json")))
W, H = TL.get("width", 1920), TL.get("height", 1080)
scenes = sorted(TL["scenes"], key=lambda s: (s["start"], s.get("track", 1)))

ids = [s["id"] for s in scenes]
if len(ids) != len(set(ids)):
    sys.exit("timeline.json: duplicate scene ids")
for s in scenes:
    src = os.path.join(ROOT, "compositions", s["src"])
    if not os.path.exists(src):
        sys.exit(f"timeline.json: {s['id']} points at a missing file {src}")

total = round(max(s["start"] + s["dur"] for s in scenes), 3)
hosts = "\n".join(
    f'      <div id="{s["id"]}" class="scene clip" data-composition-id="{s["id"]}" data-composition-src="compositions/{s["src"]}"\n'
    f'        data-start="{s["start"]}" data-duration="{s["dur"]}" data-track-index="{s.get("track", 1)}" data-width="{W}" data-height="{H}"></div>'
    for s in scenes)
block = (f"      <!-- scenes:begin (generated by tools/build_index.py) -->\n{hosts}\n\n"
         f'      <audio id="score" src="assets/audio/score.wav" data-start="0" data-duration="{total}" data-track-index="20" data-volume="1"></audio>\n'
         f"      <!-- scenes:end -->")

path = os.path.join(ROOT, "index.html")
html = open(path).read()
if "<!-- scenes:begin" not in html or "<!-- scenes:end -->" not in html:
    sys.exit("index.html: add <!-- scenes:begin --> and <!-- scenes:end --> where the scene hosts belong")
html = re.sub(r"[ \t]*<!-- scenes:begin.*?<!-- scenes:end -->", lambda m: block, html, flags=re.S)
html = re.sub(r'(data-composition-id="main"[^>]*?data-duration=")[\d.]+', rf"\g<1>{total}", html, flags=re.S)
html = re.sub(r"[\d.]+(\s*/\*total\*/)", rf"{total}\g<1>", html)
html = re.sub(r"[\d.]+(\s*/\*half\*/)", rf"{round(total / 2, 3)}\g<1>", html)
open(path, "w").write(html)

gaps = [(a["id"], b["id"], round(b["start"] - (a["start"] + a["dur"]), 3))
        for a, b in zip([s for s in scenes if s.get("track", 1) == 1], [s for s in scenes if s.get("track", 1) == 1][1:])
        if abs(b["start"] - (a["start"] + a["dur"])) > 1e-6]
print(f"scenes {len(scenes)}  total {total}s")
for a, b, g in gaps:
    print(f"  track 1 {'gap' if g > 0 else 'overlap'} of {abs(g)}s between {a} and {b}")
