"""Build the subtitle composition from the voiceover: compositions/subs.html plus its timeline.json entry.

    python3 tools/subs.py

Each line in audio/vo.json is transcribed once (npx hyperframes transcribe, local whisper) for word
timings, cached as assets/audio/vo/<id>.words.json next to its wav. The subtitles show the script's
own text, one sentence per chunk, split at a comma when a sentence runs past MAX_WORDS. Whisper only
supplies the timing, so its spelling ("80" for "Eighty") never reaches the screen.
"""

import json
import os
import re
import shutil
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VO = json.load(open(os.path.join(ROOT, "audio", "vo.json")))
TL_PATH = os.path.join(ROOT, "timeline.json")
TL = json.load(open(TL_PATH))
SCENES = {s["id"]: s for s in TL["scenes"]}
VO_DIR = os.path.join(ROOT, "assets", "audio", "vo")
MAX_WORDS = 12
TAIL = 0.25  # a chunk stays up this long after its last word, unless the next chunk starts sooner


def words_for(line_id):
    wav = os.path.join(VO_DIR, f"{line_id}.wav")
    cache = os.path.join(VO_DIR, f"{line_id}.words.json")
    if os.path.exists(cache) and os.path.getmtime(cache) >= os.path.getmtime(wav):
        return json.load(open(cache))
    tmp = tempfile.mkdtemp()
    try:
        subprocess.run(["npx", "--yes", "hyperframes@0.8.77", "transcribe", wav, "--json", "-m", "small.en", "-d", tmp],
                       check=True, cwd=tmp, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        words = json.load(open(os.path.join(tmp, "transcript.json")))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    json.dump(words, open(cache, "w"))
    return words


def chunks_of(text):
    out = []
    for sentence in re.findall(r"[^.?!]+[.?!]?", text):
        sentence = sentence.strip()
        if not sentence:
            continue
        if len(sentence.split()) <= MAX_WORDS:
            out.append(sentence)
            continue
        parts = [p.strip() for p in re.split(r"(?<=,)\s", sentence)]
        cur = ""
        for p in parts:
            if cur and len((cur + " " + p).split()) > MAX_WORDS:
                out.append(cur)
                cur = p
            else:
                cur = (cur + " " + p).strip()
        if cur:
            out.append(cur)
    return out


def timing(script_words, heard, i0, i1):
    """Start and end (clip seconds) of script words i0..i1-1, mapped onto the heard words."""
    if len(heard) == len(script_words):
        return heard[i0]["start"], heard[i1 - 1]["end"]
    # Different word counts ("SFTP" heard as several words): map by the share of letters spoken so far.
    def pos(ws):
        acc, out = 0, []
        for w in ws:
            out.append(acc)
            acc += len(re.sub(r"\W", "", w)) or 1
        return out + [acc]
    sp = pos(script_words)
    hp = pos([w["text"] for w in heard])

    def at(frac):
        target = frac * hp[-1]
        for k in range(len(heard)):
            if hp[k + 1] >= target:
                w = heard[k]
                span = max(hp[k + 1] - hp[k], 1)
                return w["start"] + (w["end"] - w["start"]) * (target - hp[k]) / span
        return heard[-1]["end"]
    return at(sp[i0] / sp[-1]), at(sp[i1] / sp[-1])


cues = []
for line in VO["lines"]:
    heard = words_for(line["id"])
    if not heard:
        raise SystemExit(f"{line['id']}: transcription is empty")
    base = SCENES[line["scene"]]["start"] + float(line["t"])
    script_words = line["text"].split()
    i = 0
    for chunk in chunks_of(line["text"]):
        n = len(chunk.split())
        start, end = timing(script_words, heard, i, i + n)
        cues.append({"text": chunk.rstrip(","), "start": round(base + start - 0.05, 3), "end": round(base + end + TAIL, 3)})
        i += n
cues.sort(key=lambda c: c["start"])
for a, b in zip(cues, cues[1:]):
    a["end"] = round(min(a["end"], b["start"] - 0.04), 3)

total = round(max(s["start"] + s["dur"] for s in TL["scenes"] if s["id"] != "subs"), 3)
html = f"""<!DOCTYPE html>
<html>
  <head><meta charset="UTF-8"></head>
  <body>
    <template>
      <style>
        #subs-root {{ position: absolute; inset: 0; pointer-events: none; font-family: var(--ui); }}
        #subs-root .sub {{ position: absolute; left: 50%; bottom: 30px; transform: translateX(-50%); max-width: 1500px; padding: 10px 26px;
          border-radius: 14px; background: color-mix(in srgb, var(--canvas) 82%, transparent); color: var(--ink); font-size: 38px; font-weight: 600; line-height: 1.3;
          letter-spacing: -0.005em; text-align: center; white-space: nowrap; opacity: 0; }}
      </style>
      <div id="subs-root" data-composition-id="subs" data-width="1920" data-height="1080"></div>
      <script>
        (() => {{
          // Generated by tools/subs.py from audio/vo.json and the whisper word timings. Do not edit by hand.
          const CUES = {json.dumps(cues)};
          const root = document.getElementById("subs-root");
          const tl = gsap.timeline({{ paused: true }});
          CUES.forEach((c, i) => {{
            const el = document.createElement("div");
            el.className = "sub"; el.id = `subs-c${{i}}`; el.setAttribute("data-layout-ignore", "");
            el.textContent = c.text;
            root.appendChild(el);
            tl.fromTo(el, {{ opacity: 0, y: 8 }}, {{ opacity: 1, y: 0, duration: 0.12, ease: "power2.out", immediateRender: false }}, c.start);
            tl.to(el, {{ opacity: 0, duration: 0.1 }}, Math.max(c.start + 0.2, c.end - 0.1));
          }});
          tl.set({{}}, {{}}, {total});
          window.__timelines["subs"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
open(os.path.join(ROOT, "compositions", "subs.html"), "w").write(html)
entry = {"id": "subs", "src": "subs.html", "track": 4, "start": 0, "dur": total}
TL["scenes"] = [s for s in TL["scenes"] if s["id"] != "subs"] + [entry]
json.dump(TL, open(TL_PATH, "w"), indent=2)
print(f"{len(cues)} subtitle chunks over {total}s")
for c in cues:
    print(f"  {c['start']:7.2f}-{c['end']:7.2f}  {c['text']}")
